name: main
# run nightly
on:
  schedule:
  - cron: "*/10 * * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: |
        # activate virtual environment
        python -m venv venv
        . venv/bin/activate
        python -m pip install -r requirements.txt
        python3 site-generator/generate.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update site
        commit_options: '--no-verify'
        commit_user_name: GitHub Actions
        commit_user_email: github-actions[bot]@users.noreply.github.com
        commit_author: GitHub Actions <github-actions[bot]@users.noreply.github.com>
        file_pattern: index.html


