name: publish kevbadge to npm if new version
# TODO: run nightly
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: site-deploy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: |
          cd site-generator
          npm install
          npm test
      # publish kevbadge to https://www.npmjs.com/package/kevbadge
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: site-generator/package.json
